language: nix

before_install:
  - nix-env -f "<nixpkgs>" -iA bash stack git xz gnumake
  - git clone https://github.com/eth-r/codecov-haskell
  - cd codecov-haskell
  - stack install .
  - cd ..

install:
  - stack setup

script:
  - stack test --coverage --haddock
  - mkdir -p dist/phc/tix
  - cp -r $(stack path --local-hpc-root)/sized-memory dist/phc/tix
  - codecov-haskell sized-memory-tests
