language: nix

before_install:
  - nix-env -f "<nixpkgs>" -iA bash stack git xz gnumake
  - git clone https://github.com/eth-r/codecov-haskell
  - cd codecov-haskell
  - stack install .
  - cd ..

install:
  - stack setup

script:
  - stack test --coverage --haddock
  - stack hpc report sized-memory-tests $(stack path --local-hpc-root)/sized-memory/all/all.tix
  - /home/travis/.local/bin/codecov-haskell --tix-dir=$(stack path --local-hpc-root)/sized-memory/ --mix-dir=$(stack path --dist-dir)/hpc/ sized-memory-tests
